### ISSUE TITLE
Feat: Set up basic project structure

### ISSUE THREAD

**Issue by cla6shade** [ApptiveDev/apptive-19th-marico-frontend#5]
## Description

지난 회의에서 프로젝트 틀은 여러 액션들에 대한 리덕스 모듈을 만들어 RootReducer로 묶고 각 컴포넌트에서 사용할 수 있도록 설계하도록 결정했습니다.

Ref - [4. 리덕스 모듈 만들기](https://react.vlpt.us/redux/04-make-modules.html)

## To-Do
- [x] 지난번 커밋에서 등록했던 aliases에 따라 import문 수정 (e.g. import './App.css' => import '@css/App.css')
- [x] Root Reducer 모듈 만들기
- [x] 로그인 redux 모듈 생성, 적절하게 action과 action 생성함수, reducer 함수 생성(e.g. auth/LOGIN, auth/LOGOUT 등)
- [ ] 회원 정보에 대한 Interface 생성(정해진 틀 안에서 회원 정보와 JWT 토큰을 관리하기 위함입니다. 이 부분은 어떤 정보를 담으면 좋을지 조금 생각해봐야 될 것 같네요) 

## ETC

login/logout외에도 기획상에서 필요한 액션들을 미리 하나씩 생각해두면 나중에 구현할 때 조금 더 편할지 않을까 싶습니다.
추가 의견 있으시면 편하게 남겨주시면 감사하겠습니다!

**Comment by KIJUNG-CHAE** [comment]
To do 1, 2번은 이견없습니다! 필요한 액션들 구상 + 3,4번은 레퍼런스 참고하면서 깊이 생각해보고 싶은데, 아마 같은 레퍼런스를 참고하여 방향성이 다를 것 같진 않습니다. 목요일까지 확인하여 코멘트 남기겠습니다!

**Comment by cla6shade** [comment]
# 약간의 구조 수정

루트 리듀서를 만들고 createStore로 리덕스 스토어를 만들어서 Provider로 하위 컴포넌트에 전달하는 것이 정해진 방식이었습니다.

그러나 createStore이 deprecate가 예정됨에 따라 @reduxjs/toolkit의 configureStore 메소드를 이용하고자 합니다. 
configureStore 메소드는 createStore과 동일한 기능을 하지만 여러 리듀서들을 루트 리듀서로 자동으로 통합하는 기능을 지원하고, 미들웨어 적용도 하나의 메소드로 간편하게 할 수 있다고 합니다. 

정리하면,

## 원래 방식
```typescript
// modules/index.ts
import {combineReducers} from 'redux';
import authReducer from '@modules/auth.ts';

const rootReducer = combineReducers({
  authReducer
});
export default rootReducer;
```
```typescript
// main.tsx

//...import statements
const store = createStore(rootReducer);

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <Provider store={store}>
      <App />
    </Provider>
  </React.StrictMode>,
);
```

## 바꿀 방식
```typescript
// modules/index.ts 제거
```
```typescript
// main.tsx

//...import statements
const store = configureStore({
  reducer: {
    auth: authReducer,
  },
});

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <Provider store={store}>
      <App />
    </Provider>
  </React.StrictMode>,
);
```
